### ISSUE TITLE
`register_entity` should handle `remove_versions`

### ISSUE THREAD

**Issue by mpietras-p4** [Paradigm4/revealcore#35]
`register_entity` should call `remove_versions` to avoid ballooning number of array versions.  Possibly make this a per-array config setting in the schema yaml?  What should the default be?

**Comment by ksens** [comment]
@mpietras-p4 

- Biobank saves only the last version of the array 
- In SC, we choose to save last 5 versions of the array (see https://github.com/Paradigm4/reveal-singlecell/blob/03867ffdf302db85d3d6d9be8c6a8c55167ab266/revealsc/R/scidb-helper-functions.R#L158)

**Comment by agvandervelde** [comment]
proteomics doesn't care about array versions and, somewhat inconsistently, cleans up old versions.

**Comment by mpietras-p4** [comment]
@ksens @agvandervelde I'm setting the default behavior to be "remove all versions except the latest".  If you want to keep more than the latest, you can set `keep_versions` in the array schema to a different value (or `NULL`, to keep all versions).  Does that sound reasonable?

**Comment by ksens** [comment]
Fine with me.

**Comment by agvandervelde** [comment]
Works for me.
